name: Deploy to EC2
on: 
  push:
    branches:
      - main
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to EC2 using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/ubuntu/app
          git pull origin main
          docker stop erajaya-test
          docker rm erajaya-test
          docker rmi erajaya-app:latest
          docker build -t erajaya-app:latest .
          docker run -d --restart unless-stopped -p 80:8080 --name erajaya-test erajaya-app:latest